// Central registry of tool pages — used for auto-breadcrumbs and footer link clusters.
// href (with trailing slash) -> { name, cat }
export type ToolCat = "image" | "pdf" | "doc" | "calc" | "util" | "dev";

export const TOOLS: Record<string, { name: string; cat: ToolCat }> = {
  // Image
  "/image-compressor/": { name: "Image Compressor", cat: "image" },
  "/image-resizer/": { name: "Image Resizer", cat: "image" },
  "/passport-photo-maker/": { name: "Passport Photo Maker", cat: "image" },
  "/signature-resize/": { name: "Signature Resize", cat: "image" },
  "/remove-background/": { name: "Remove Background", cat: "image" },
  "/crop-image/": { name: "Crop Image", cat: "image" },
  "/image-converter/": { name: "Image Converter", cat: "image" },
  "/photo-signature-combiner/": { name: "Photo & Signature Combiner", cat: "image" },
  "/photo-joiner/": { name: "Photo Joiner", cat: "image" },
  "/image-joiner/": { name: "Image Joiner", cat: "image" },
  "/social-media-image-resizer/": { name: "Social Media Image Resizer", cat: "image" },
  "/jpeg-to-jpg/": { name: "JPEG to JPG Converter", cat: "image" },
  "/png-to-jpg/": { name: "PNG to JPG Converter", cat: "image" },
  "/resize-image-in-kb/": { name: "Resize Image in KB", cat: "image" },
  "/increase-image-size-in-kb/": { name: "Increase Image Size in KB", cat: "image" },
  "/resize-image-in-cm/": { name: "Resize Image in CM", cat: "image" },
  "/change-image-dpi/": { name: "Change Image DPI", cat: "image" },
  "/resize-image-for-whatsapp-dp/": { name: "WhatsApp DP Resizer", cat: "image" },
  "/resize-for-pan-card/": { name: "PAN Card Photo", cat: "image" },
  "/heic-to-jpg/": { name: "HEIC to JPG Converter", cat: "image" },
  "/webp-to-jpg/": { name: "WebP to JPG Converter", cat: "image" },
  "/text-to-image/": { name: "Text to Image", cat: "image" },
  "/jfif-to-jpg/": { name: "JFIF to JPG Converter", cat: "image" },
  "/jfif-to-png/": { name: "JFIF to PNG Converter", cat: "image" },
  "/bmp-to-jpg/": { name: "BMP to JPG Converter", cat: "image" },
  "/avif-to-jpg/": { name: "AVIF to JPG Converter", cat: "image" },
  // PDF
  "/pdf/jpg-to-pdf/": { name: "JPG to PDF", cat: "pdf" },
  "/pdf/pdf-to-jpg/": { name: "PDF to JPG", cat: "pdf" },
  "/pdf/merge/": { name: "Merge PDF", cat: "pdf" },
  "/pdf/compress/": { name: "Compress PDF", cat: "pdf" },
  "/pdf/split/": { name: "Split PDF", cat: "pdf" },
  "/pdf/rotate/": { name: "Rotate PDF", cat: "pdf" },
  "/pdf/delete-pages/": { name: "Delete PDF Pages", cat: "pdf" },
  "/pdf/page-numbers/": { name: "Add Page Numbers to PDF", cat: "pdf" },
  "/pdf/watermark/": { name: "Watermark PDF", cat: "pdf" },
  "/pdf/organize/": { name: "Organize PDF", cat: "pdf" },
  "/resize-pdf/": { name: "Resize PDF", cat: "pdf" },
  "/heic-to-pdf/": { name: "HEIC to PDF Converter", cat: "pdf" },
  "/webp-to-pdf/": { name: "WebP to PDF Converter", cat: "pdf" },
  "/compress-pdf-for-uscis/": { name: "Compress PDF for USCIS", cat: "pdf" },
  "/compress-resume-pdf/": { name: "Compress Resume PDF", cat: "pdf" },
  "/combine-bank-statements-pdf/": { name: "Combine Bank Statements PDF", cat: "pdf" },
  "/reduce-pdf-size-for-visa-application/": { name: "Reduce PDF Size for Visa", cat: "pdf" },
  // Documents
  "/resume-maker/": { name: "Resume Maker", cat: "doc" },
  "/marriage-biodata-maker/": { name: "Marriage Biodata Maker", cat: "doc" },
  "/cover-letter-generator/": { name: "Cover Letter Generator", cat: "doc" },
  "/invoice-generator/": { name: "Invoice Generator", cat: "doc" },
  "/email-signature-maker/": { name: "Email Signature Maker", cat: "doc" },
  // Calculators
  "/emi-calculator/": { name: "EMI Calculator", cat: "calc" },
  "/sip-calculator/": { name: "SIP Calculator", cat: "calc" },
  "/gst-calculator/": { name: "GST Calculator", cat: "calc" },
  "/interest-calculator/": { name: "Interest Calculator", cat: "calc" },
  "/percentage-calculator/": { name: "Percentage Calculator", cat: "calc" },
  "/marks-percentage-calculator/": { name: "Marks % & CGPA Calculator", cat: "calc" },
  "/tdee-calculator/": { name: "TDEE Calculator", cat: "calc" },
  "/pregnancy-calculator/": { name: "Pregnancy Calculator", cat: "calc" },
  "/dog-age-calculator/": { name: "Dog Age Calculator", cat: "calc" },
  // Utilities
  "/age-calculator/": { name: "Age Calculator", cat: "util" },
  "/qr-code-generator/": { name: "QR Code Generator", cat: "util" },
  "/word-counter/": { name: "Word Counter", cat: "util" },
  "/typing-test/": { name: "Typing Test", cat: "util" },
  "/password-generator/": { name: "Password Generator", cat: "util" },
  "/text-case-converter/": { name: "Text Case Converter", cat: "util" },
  "/date-difference-calculator/": { name: "Date Difference Calculator", cat: "util" },
  "/unit-converter/": { name: "Unit Converter", cat: "util" },
  // Developer Tools
  "/json-formatter/": { name: "JSON Formatter", cat: "dev" },
  "/base64-encode-decode/": { name: "Base64 Encode/Decode", cat: "dev" },
  "/url-encode-decode/": { name: "URL Encode/Decode", cat: "dev" },
  "/hash-generator/": { name: "Hash Generator", cat: "dev" },
  "/lorem-ipsum-generator/": { name: "Lorem Ipsum Generator", cat: "dev" },
  "/uuid-generator/": { name: "UUID Generator", cat: "dev" },
  "/timestamp-converter/": { name: "Unix Timestamp Converter", cat: "dev" },
  "/color-converter/": { name: "Color Converter", cat: "dev" },
  "/csv-to-json/": { name: "CSV to JSON Converter", cat: "dev" },
  "/csv-to-pdf/": { name: "CSV to PDF Converter", cat: "dev" },
  "/text-to-html/": { name: "Text to HTML Converter", cat: "dev" },
  "/text-to-xml/": { name: "Text to XML Converter", cat: "dev" },
  "/text-to-json/": { name: "Text to JSON Converter", cat: "dev" },
};
